appName: "coffee shop"
appEnv: "dev"
appPort: 8080
jwt:
  secrets: "123456"
  expireminutes: 20
database:
  host: "127.0.0.1"
  port: 5432
  user: "fazztrack"
  namedb: "coffeeshop_database"
  pass: "123456"
cloudinary:
  name: "dgshxa0xm"
  key: "665975824159148"
  sec: "LDKbdogsUhYGLjZDqTwzVD6jGLM"